version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=metsenat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
  web:
    build: .
    command: python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
#      - "8003:8000"
      - "8000:8000"
    environment:
      - POSTGRES_NAME=metsenat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    depends_on:
      - db