# Generated by Django 4.0.5 on 2022-06-12 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('sponsorship_amount', models.FloatField(blank=True, null=True)),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'bank'), (2, 'click'), (3, 'payme'), (4, 'cash'), (5, 'other')], default=4)),
                ('sponsor_type', models.PositiveSmallIntegerField(choices=[(1, 'legal_entity'), (2, 'individual')], default=2)),
                ('company_name', models.CharField(default='not_legal_entity', max_length=100)),
                ('sponsor_image', models.ImageField(blank=True, null=True, upload_to='profile/sponsor_image/')),
                ('application_status', models.CharField(choices=[('yangi', 'yangi'), ('tasdiqlangan', 'tasdiqlangan'), ('moderatsiyada', 'moderatsiyada'), ('bekor_qilingan', 'bekor_qilingan')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('contract_amount', models.FloatField()),
                ('type_student', models.CharField(choices=[('bachelor', 'bachelor'), ('magister', 'magister')], default='bachelor', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/sponsor_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('OTM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.otm')),
                ('sponsor', models.ManyToManyField(to='index.sponsor')),
            ],
        ),
    ]
